default: &default
  adapter: 'sqlite3'
  database: 'db/development.sqlite'

development:
  <<: *default

test:
  <<: *default
  database: 'db/test.sqlite'

production:
    adapter: postgresql
    database: 'db/production.pg'
    pool: 5
    timeout: 5000